
<h2> Previsão de curtida com ML </h2>
 previsão de curtidas pela a idade tempo turno e estado da pessoa

In [43]:
import pandas as pd

# ler os dados
df = pd.read_csv('curtidas.csv')
df

    Age  time state shift like
0    36     5    Ba     N   NO
1    42     3    Es     N  YES
2    23     1    Rj     D   NO
3    52     2    Es     N   NO
4    18     5    Rj     D  YES
5    16     6    Es     D  YES
6    31     3    Ba     N   NO
7    34     1    Ba     D   NO
8    17     2    Es     D   NO
9    24     7    Es     N  YES
10   67     1    Rj     N   NO
11   26     2    Ba     D  YES

In [44]:
# Altere os valores da string para valor numerioco

d = {'N':0,'D':1}
df['shift'] = df['shift'].map(d)
d = {'Ba':0,'Es':1,'Rj':2}
df['state'] = df['state'].map(d)
d = {'YES':1,'NO':0}
df['like'] = df['like'].map(d)

In [45]:
# Então temos que separa as colunar de recursos da coluna de destino
# X são as colunas de recursos, y é a coluna de destino

# previsão de dados manual



features = ['Age','time','state','shift']

X = df[features]
y = df['like']

print(X)
print(y)

    Age  time  state  shift
0    36     5      0      0
1    42     3      1      0
2    23     1      2      1
3    52     2      1      0
4    18     5      2      1
5    16     6      1      1
6    31     3      0      0
7    34     1      0      1
8    17     2      1      1
9    24     7      1      0
10   67     1      2      0
11   26     2      0      1
0     0
1     1
2     0
3     0
4     1
5     1
6     0
7     0
8     0
9     1
10    0
11    1
Name: like, dtype: int64

In [46]:
# Previsão de dados ML

import pandas 
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

In [56]:
df = pandas.read_csv('curtidas.csv')

d = {'N':0,'D':1}
df['shift'] = df['shift'].map(d)
d = {'Ba':0,'Es':1,'Rj':2}
df['state'] = df['state'].map(d)
d = {'YES':1,'NO':0}
df['like'] = df['like'].map(d)

features = ['Age','time','state','shift']

X = df[features]
y = df['like']

dtree = DecisionTreeClassifier()
dtree = dtree.fit(X, y)

print(dtree.predict([[31,3,0,1]]))
print("no like[0]")
print("yes like[1]")

[0]
no like[0]
yes like[1]